services:
  backend:
    build: .
    ports:
      - "3000:3000"
    # Solo monta el código fuente, no node_modules
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: npm run dev